### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by neakor** [uber/needle#300]
Looks like the last commit broke the build somehow?

**Comment by rudro** [comment]
SPM depends on `llbuild`, and in more recent versions, just asks for the `master` branch of `llbuild`.  This is problematic because llbuild master is asking for the SPM 5.0 package syntax, etc. So I rolled back SPM to `0.3.0`. Will change this once our CI machines are beyond `10.14.3` and we're able to drop static linking (and hence move to Xcode 10.2 and beyond).

**Comment by neakor** [comment]
Nice! Thank you!
