### ISSUE TITLE
If generated file hasn't changed, don't write it

### ISSUE THREAD

**Issue by brentleyjones** [uber/needle#311]
To prevent Xcode from rebuilding the the target that includes the generated swift file `needle` should not write the file to disk if the output would be the same as what already exists.

**Comment by rudro** [comment]
This is a great suggestion and I will try to get to it soon(ish).  Some build systems like buck and bazel use the SHA of the contents and realize that no change as occurred. However, that's clearly not true for Xcode which get's confused when we rewire the file with the exact same contents.

We'll update to write to a temp file and diff before moving.

**Comment by ffittschen** [comment]
Hi @rudro, recently we discovered this behavior as well as we investigated our build times. Looking at other tools that generate code, they also avoid to write the destination file if the content is unchanged, but they usually read the content if the destination file already exists and then write if needed instead of always writing and then moving. (See [SwiftGen](https://github.com/SwiftGen/SwiftGen/blob/stable/Sources/SwiftGen/Commander/OutputDestination.swift#L32-L44) or [R.swift](https://github.com/mac-cain13/R.swift/blob/master/Sources/RswiftCore/RswiftCore.swift#L180-L188))

Did you already start working on this or could I open a PR with the changes?
