### ISSUE TITLE
SwiftSyntax issue with binary from Homebrew

### ISSUE THREAD

**Issue by morozkin** [uber/needle#374]
Hi there!

I faced with the following issue using 0.16.2 version that I installed via Homebrew.

The error output looks like: `error: 💩 Unknown error: SwiftSyntax parser library isn't compatible`

Seems like there is a missed detail for distribution of the latest version via Homebrew.

There is no issue if I'm using the binary with the provided version of `lib_InternalSwiftSyntaxParser.dylib` from the repository.

**Comment by morozkin** [comment]
@rudro @tianskylan take a look please

**Comment by tianskylan** [comment]
@morozkin I'll take a look today and tomorrow to see what's going on with the Homebrew distribution. The workaround you mentioned should work in the mean time.

**Comment by tianskylan** [comment]
Homebrew CI complains about my new distribution with the fix: https://github.com/Homebrew/homebrew-core/pull/64274.
Investigating what we can do here.

**Comment by morozkin** [comment]
I checked the latest version `0.16.2.2` from Homebrew and the error is still here 😢

**Comment by tianskylan** [comment]
Ok I think I know why now. Will take a look this afternoon.

@rudro I removed `clean` before running `archive_generator`, because it causes some weird build failure on brew. However, apparently without that `clean`, the needle binary would complain about incompatible swiftsyntax parser. Very surprising to me

**Comment by tianskylan** [comment]
Ok the problem is with the Xcode version that Homebrew uses to build needle.
We specified 11.6 in the formula, but Homebrew uses Xcode 12 to build it anyway. Looks like `11.6` was interpreted as the minimum version.

A couple options:
- Figure out how to specify a specific version in Homebrew formula, for Xcode.
- Upgrade needle to latest SwiftSyntax and Xcode 12. (ref #365)

I'll investigate option 1 first. If not, I'll work on option 2.

**Comment by morozkin** [comment]
Everything is fine with `0.17.0` 🎉 

It was a little bit tricky to make it work. Thanks a lot for all your efforts @tianskylan 💪🏻
